    # -*- coding: utf-8 -*-
    """THERMODYNAMICS U3.ipynb

    Automatically generated by Colab.

    Original file is located at
        https://colab.research.google.com/drive/1ctOGf8dZn2nLl547SB7Eho6pGsZTAVyl
    """

    !pip install CoolProp



    # Potencia de salida de la turbina (CODIGO NO COMPROBADO)
    import math
    from CoolProp.CoolProp import PropsSI

    def calcular_velocidad_salida(d1, d2, v1, vesp1, vesp2):
        """
        Calcula la velocidad de salida v2 utilizando la conservación de la masa.
        """

        A1 = math.pi * (d1 / 2) ** 2
        A2 = math.pi * (d2 / 2) ** 2


        rho1 = 1 / vesp1  # lbm/ft^3
        rho2 = 1 / vesp2  # lbm/ft^3


        v2 = (rho1 * A1 * v1) / (rho2 * A2)
        return v2

    def calcular_potencia(d1, d2, v1, v2, h1, h2, vesp1, vesp2):
        """
        Calcula la potencia de salida de la turbina.
        """
        # Conversión de diámetros a áreas (ft^2)
        A1 = math.pi * (d1 / 2) ** 2
        A2 = math.pi * (d2 / 2) ** 2

        # Densidades (1 / volumen específico)
        rho1 = 1 / vesp1  # lbm/ft^3
        rho2 = 1 / vesp2  # lbm/ft^3

        # Gasto másico (lbm/s)
        mdot = rho1 * A1 * v1

        # Velocidades cuadradas
        v1_squared = v1 ** 2
        v2_squared = v2 ** 2

        # Potencia (ft-lbf/s)
        potencia = mdot * ((h1 - h2) + (v1_squared - v2_squared) / 2)

        # Conversión a caballos de fuerza (hp)
        potencia_hp = potencia / 550  # 1 hp = 550 ft-lbf/s

        return potencia_hp

    def main():
        print("Cálculo de la potencia de salida de una turbina")
        print("------------------------------------------------")

        # Datos iniciales
        try:
            # Entrada de diámetros en pulgadas
            d1_in = float(input("Ingrese el diámetro de la entrada (en pulgadas): "))
            d2_in = float(input("Ingrese el diámetro de la salida (en pulgadas): "))

            # Conversión de diámetros de pulgadas a pies
            d1 = d1_in / 12  # 1 pie = 12 pulgadas
            d2 = d2_in / 12

            # Entrada de velocidad y condiciones de estado
            v1 = float(input("Ingrese la velocidad en la entrada (en ft/s): "))
            P1 = float(input("Ingrese la presión en la entrada (en psia): "))
            T1 = float(input("Ingrese la temperatura en la entrada (en °F): "))
            P2 = float(input("Ingrese la presión en la salida (en psia): "))
            T2 = float(input("Ingrese la temperatura en la salida (en °F): "))

            # Convertir unidades de entrada a SI para CoolProp
            P1_SI = P1 * 6894.76  # psia a Pa
            T1_SI = (T1 - 32) * 5/9 + 273.15  # °F a K
            P2_SI = P2 * 6894.76  # psia a Pa
            T2_SI = (T2 - 32) * 5/9 + 273.15  # °F a K

            # Consultar propiedades con CoolProp
            h1 = PropsSI('H', 'P', P1_SI, 'T', T1_SI, 'Water') / 1055.06  # J/kg a BTU/lbm
            h2 = PropsSI('H', 'P', P2_SI, 'T', T2_SI, 'Water') / 1055.06  # J/kg a BTU/lbm
            vesp1 = PropsSI('V', 'P', P1_SI, 'T', T1_SI, 'Water') * 35.3147  # m^3/kg a ft^3/lbm
            vesp2 = PropsSI('V', 'P', P2_SI, 'T', T2_SI, 'Water') * 35.3147  # m^3/kg a ft^3/lbm

            # Calcular velocidad de salida
            v2 = calcular_velocidad_salida(d1, d2, v1, vesp1, vesp2)

            # Calcular potencia
            potencia = calcular_potencia(d1, d2, v1, v2, h1, h2, vesp1, vesp2)
            print(f"\nVelocidad de salida: {v2:.2f} ft/s")
            print(f"La potencia de salida de la turbina es: {potencia:.2f} hp")

        except ValueError:
            print("Error: Por favor, ingrese valores numéricos válidos.")
        except Exception as e:
            print(f"Ha ocurrido un error inesperado: {e}")

    if __name__ == "__main__":
        main()

    # Diámetro de salida
    import math

    def calcular_velocidad_salida(h1, h2, v1):
        """
        Calcula la velocidad de salida v2 utilizando la ecuación de energía.
        """
        v2 = (((v1 ** 2) - 2 * (h2 - h1)))
        return v2

    def calcular_diametro_salida(d1, v1, v2, V1, V2):
        """
        Calcula el diámetro de salida d2 usando la ecuación de continuidad.
        """
        d2 = math.sqrt((d1**2 * v1)/v2)
        return d2

    def main():
        print("Cálculo del diámetro de salida de una boquilla convergente")
        print("----------------------------------------------------------")

        try:
            # Entrada de datos iniciales
            d1 = float(input("Ingrese el diámetro de entrada d1 (en cm): "))
            h1 = float(input("Ingrese la entalpía a la entrada h1 (en kJ/kg): "))
            h2 = float(input("Ingrese la entalpía a la salida h2 (en kJ/kg): "))
            v1 = float(input("Ingrese la velocidad a la entrada v1 (en m/s): "))
            V1 = float(input("Ingrese el volumen específico a la entrada V1 (en cm^3/g): ")) / 1000  # Convertir a m^3/kg
            V2 = float(input("Ingrese el volumen específico a la salida V2 (en cm^3/g): ")) / 1000  # Convertir a m^3/kg

            # Cálculo de la velocidad de salida
            v2 = calcular_velocidad_salida(h1, h2, v1)
            print(f"\nVelocidad de salida v2 calculada: {v2} m/s")

            # Cálculo del diámetro de salida
            d2 = calcular_diametro_salida(d1, v1, v2, V1, V2)
            print(f"Diámetro de salida d2 calculado: {d2} cm")

        except ValueError:
            print("Error: Por favor, asegúrese de ingresar valores numéricos válidos.")25
        main()

    !pip install CoolProp

    # Función para la velocidad del vapor de agua
    try:
        from CoolProp.CoolProp import PropsSI
    except ImportError:
        print("La biblioteca CoolProp no está instalada. Instálala usando 'pip install CoolProp' para utilizar las propiedades termodinámicas de agua.")

    import math

    def calcular_velocidad_salida():
        print("Cálculo de la velocidad de salida del vapor de agua en una tobera")

        # Ingreso de datos
        T_entrada = float(input("Ingrese la temperatura de entrada (°C): ")) + 273.15  # Convertimos °C a K
        P_entrada = float(input("Ingrese la presión de entrada (kPa): ")) * 1000  # Convertimos kPa a Pa
        T_salida = float(input("Ingrese la temperatura de salida (°C): ")) + 273.15  # Convertimos °C a K
        P_salida = float(input("Ingrese la presión de salida (kPa): ")) * 1000  # Convertimos kPa a Pa
        v_entrada = float(input("Ingrese la velocidad de entrada (m/s): "))
        Q_perdida = float(input("Ingrese la tasa de pérdida de calor (kW): ")) * 1000  # Convertimos kW a W
        A_entrada = float(input("Ingrese el área de entrada (cm²): ")) * 1e-4  # Convertimos cm² a m²

        # Cálculo de entalpías y densidad usando CoolProp
        h_entrada = PropsSI('H', 'P', P_entrada, 'T', T_entrada, 'Water')  # En J/kg
        h_salida = PropsSI('H', 'P', P_salida, 'T', T_salida, 'Water')  # En J/kg
        rho_entrada = PropsSI('D', 'P', P_entrada, 'T', T_entrada, 'Water')  # En kg/m³

        # Cálculo del flujo másico
        m_dot = rho_entrada * v_entrada * A_entrada

        # Aplicación de la ecuación de conservación de la energía para despejar la velocidad de salida
        v_salida = math.sqrt(2 * ((h_entrada - h_salida - (Q_perdida / m_dot)) + (v_entrada**2 / 2)))

        # Resultado
        print(f"La velocidad de salida del vapor de agua es: {v_salida:.2f} m/s")

    # Llamar a la función para ejecutar el cálculo
    calcular_velocidad_salida()

    # Energía transferida como trabajo (SI LA ENERGÍA DISMINUYE, EL RESULTADO SERA - .SI LA ENERGIA AUMENTA, EL RESULTADO SERA +)
    def calcular_trabajo(Q, delta_U):
        """
        Calcula la energía transferida como trabajo utilizando la primera ley de la termodinámica.
        """
        # Primera ley de la termodinámica: Q = ΔU + W => W = Q - ΔU
        W = Q - (delta_U)  # Cambiamos el signo de
        return W

    def main():
        print("Cálculo de la energía transferida como trabajo en un sistema cerrado")
        print("--------------------------------------------------------------------")

        try:
            # Entrada de datos iniciales
            Q = float(input("Ingrese la cantidad de calor añadida al sistema (en kJ, positivo si es calor añadido): "))
            delta_U = float(input("Ingrese el cambio en la energía interna del sistema (en kJ, positivo si aumenta): "))

            # Cálculo del trabajo
            W = calcular_trabajo(Q, delta_U)
            print(f"\nEnergía transferida como trabajo: {W} kJ")

        except ValueError:
            print("Error: Por favor, asegúrese de ingresar valores numéricos válidos.")
        except Exception as e:
            print(f"Ha ocurrido un error inesperado: {e}")

    if __name__ == "__main__":
        main()

    # Función para calcular el calor transferido en serpentin (SE MANTIENE EL SIGNO DEL RESULTADO QUE SE GENERE)
    def calcular_calor_transferido():
        print("Cálculo del calor transferido por unidad de masa de agua en un serpentín")

        # Ingreso de datos
        h_entrada = float(input("Ingrese la entalpía de entrada (kJ/kg): "))
        h_salida = float(input("Ingrese la entalpía de salida (kJ/kg): "))
        v_entrada = float(input("Ingrese la velocidad de entrada (m/s): "))
        v_salida = float(input("Ingrese la velocidad de salida (m/s): "))

        # Cálculo del cambio de energía cinética
        delta_energia_cinetica = (v_salida**2 - v_entrada**2) / 2 / 1000  # Convierte J/kg a kJ/kg

        # Cálculo del calor transferido por unidad de masa
        q = h_salida - h_entrada + delta_energia_cinetica

        # Resultado
        print(f"El calor transferido por unidad de masa es: {q:.2f} kJ/kg")

    # Llamar a la función para ejecutar el cálculo
    calcular_calor_transferido()

    # Función para calcular la entalpía
    def calcular_entalpia():
        print("Cálculo de la entalpía específica")

        # Ingreso de datos
        u = float(input("Ingrese la energía interna específica (kJ/kg): "))
        P = float(input("Ingrese la presión (kPa): "))
        v = float(input("Ingrese el volumen específico (cm³/g): "))

        # Conversión de unidades: cm³/g a m³/kg
        v_m3_kg = v * 1e-3  # cm³/g a m³/kg

        # Cálculo de la entalpía
        h = u + P * v_m3_kg

        # Resultado
        print(f"La entalpía específica es: {h:.2f} kJ/kg")

    # Llamar a la función para ejecutar el cálculo
    calcular_entalpia()

    # Calculo del tiempo para aumentar la temperatura del agua
    def calcular_tiempo():
        print("Cálculo del tiempo para aumentar la temperatura del agua")
        print("------------------------------------------------------")

        # Ingresar datos
        try:
            masa = float(input("Ingresa la masa del agua (kg): "))
            temp_inicial = float(input("Ingresa la temperatura inicial del agua (°C): "))
            temp_final = float(input("Ingresa la temperatura final deseada del agua (°C): "))
            cp = float(input("Ingresa el calor específico del agua (kJ/kg°C): "))
            potencia = float(input("Ingresa la potencia del agitador (kW): "))

            # Calcular cambio de temperatura
            delta_T = temp_final - temp_inicial

            # Calcular tiempo en segundos
            tiempo = (masa * cp * delta_T) / potencia

            print(f"\nEl tiempo necesario para que el agua alcance la temperatura deseada es: {tiempo:.2f} segundos.")

        except ValueError:
            print("Error: Por favor, ingresa valores numéricos válidos.")

    # Llamada a la función principal
    calcular_tiempo()

    # Flujo volumétrico de salida
    import math

    # Constante de los gases ideales en J/(mol K)
    R = 8.314

    # Función para calcular el flujo volumétrico en la salida de la tobera
    def calcular_flujo_volumetrico_salida(T1, P1, velocidad_entrada, T2, P2, perdida_calor, area_entrada):
        # Conversión de unidades
        area_entrada_m2 = area_entrada / 10000  # cm² a m²
        T1_kelvin = T1 + 273.15  # Convertir temperatura a Kelvin
        T2_kelvin = T2 + 273.15  # Convertir temperatura a Kelvin
        perdida_calor_watts = perdida_calor * 1000  # kW a W

        # Suposiciones:
        # - Proceso adiabático si ignoramos las pérdidas de calor (para simplificación)
        # - Velocidad de salida asumiendo que la conservación de energía en flujo es aplicable

        # Energía por conservación de energía (trabajo mecánico y calor)
        h1 = R * T1_kelvin  # Asumir H1 en función de T1 para simplificación
        h2 = h1 - perdida_calor_watts  # Asumir H2 = H1 - pérdida de calor

        # Velocidad de salida usando conservación de energía: V2
        velocidad_salida = math.sqrt(velocidad_entrada**2 + 2 * (h1 - h2))

        # Flujo másico: ṁ = (densidad1 * area_entrada * velocidad_entrada)
        # Simplificación con gas ideal
        densidad1 = P1 * 1000 / (R * T1_kelvin)
        flujo_masico = densidad1 * area_entrada_m2 * velocidad_entrada

        # Densidad de salida
        densidad2 = P2 * 1000 / (R * T2_kelvin)

        # Flujo volumétrico de salida: V̇ = flujo_masico / densidad2
        flujo_volumetrico_salida = flujo_masico / densidad2

        return round(flujo_volumetrico_salida, 4)

    # Solicitar datos de entrada al usuario
    print("Ingrese los valores para calcular el flujo volumétrico en la salida de la tobera:")

    T1 = float(input("Temperatura de entrada en °C: "))
    P1 = float(input("Presión de entrada en kPa: "))
    velocidad_entrada = float(input("Velocidad de entrada en m/s: "))
    T2 = float(input("Temperatura de salida en °C: "))
    P2 = float(input("Presión de salida en kPa: "))
    perdida_calor = float(input("Pérdida de calor en kW: "))
    area_entrada = float(input("Área de entrada en cm²: "))

    # Cálculo del flujo volumétrico en la salida
    flujo_volumetrico_salida = calcular_flujo_volumetrico_salida(T1, P1, velocidad_entrada, T2, P2, perdida_calor, area_entrada)
    print(f"\nEl flujo volumétrico en la salida de la tobera es: {flujo_volumetrico_salida} m³/s")

    # Calor transferido (con bar) (SE AGREGA EL SIGNO - AL RESULTADO)
    import math

    # Constante de los gases ideales en J/(mol K)
    R = 8.314

    # Función para calcular el calor transferido en una compresión isotérmica
    def calcular_calor_transferido(P_inicial, P_final, T):
        # Conversión de temperatura de Celsius a Kelvin
        T_kelvin = T + 273.15

        # Cálculo del trabajo (y calor transferido) en proceso isotérmico
        Q = R * T_kelvin * math.log(P_final / P_inicial)

        return round(Q, 2)

    # Solicitar datos de entrada al usuario
    print("Ingrese los valores para calcular el calor transferido durante la compresión isotérmica:")

    P_inicial = float(input("Presión inicial en bar: ")) * 1e5  # Conversión de bar a Pa
    P_final = float(input("Presión final en bar: ")) * 1e5      # Conversión de bar a Pa
    T = float(input("Temperatura en °C: "))                     # Temperatura en °C

    # Cálculo del calor transferido
    calor_transferido = calcular_calor_transferido(P_inicial, P_final, T)
    print(f"\nEl calor transferido en la compresión isotérmica es: {calor_transferido} J/mol")